name: CI

on: 
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # every day at midnight

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://koalaman/shellcheck-alpine
        with:
          args: /bin/sh -c "shellcheck -x *.sh industrial_ci/scripts/*_ci industrial_ci/src/*.sh industrial_ci/src/*/*.sh industrial_ci/*.sh"
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic}
          - {ROS_DISTRO: melodic, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: './'
        env: ${{matrix.env}}

  test_arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset --credential yes --persistent yes
      - uses: './'
        env:
          DOCKER_IMAGE: 'arm32v7/ros:melodic-ros-core'
          BEFORE_INIT: '[[ $(uname -p) == armv7l ]] && exit 42'
          EXPECT_EXIT_CODE: 42

  run_travis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          industrial_ci/scripts/run_travis
          industrial_ci/scripts/run_travis 1
