name: CI

on: 
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # every day at midnight

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://koalaman/shellcheck-alpine
        with:
          args: /bin/sh -c "shellcheck -x *.sh industrial_ci/scripts/*_ci industrial_ci/src/*.sh industrial_ci/src/*/*.sh industrial_ci/*.sh"
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic}
          - {ROS_DISTRO: melodic, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: './'
        env: ${{matrix.env}}
  industrial_ci_external:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: kinetic, _EXTERNAL_REPO: 'github:ros-industrial/industrial_core@kinetic-devel'}
          - {ROS_DISTRO: kinetic, _EXTERNAL_REPO: 'gh:ros-industrial/motoman_experimental#kinetic-devel', UPSTREAM_WORKSPACE: '.travis.rosinstall -ros-industrial/industrial_experimental/IRC_v2', ROS_REPO: ros}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - shell: bash
        env: ${{matrix.env}}
        run: |
          ./industrial_ci/_wrap_test.sh
